name: Build And Deploy to GitHub pages

on:
    push:
        branches:
            - main
        paths-ignore:
            - "*.md"
    workflow_dispatch:

permissions:
    contents: write

env:
    SITE_URL: ${{ vars.SITE_URL }}
    CDN_URL: ${{ vars.CDN_URL }}

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        if: startsWith(github.event.head_commit.message, 'deploy')
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: latest
                  run_install: false
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"
            - run: pnpm install --frozen-lockfile
            - run: pnpm build
            - uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: "./dist"
